name: toka_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  modal_progress_hud_nsn: ^0.5.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
