// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl66HbWlM5ix8BKJRGwPbI7OMhzS1mrd8',
    appId: '1:83211892689:web:6432243a4fd5d9bb2c12f0',
    messagingSenderId: '83211892689',
    projectId: 'toka-test-da174',
    authDomain: 'toka-test-da174.firebaseapp.com',
    storageBucket: 'toka-test-da174.firebasestorage.app',
    measurementId: 'G-2QQS0Q06ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKEV1XtkdQoPbg6JVLro37QuzHzNtB1-s',
    appId: '1:83211892689:android:0b1ffe12aa409ba92c12f0',
    messagingSenderId: '83211892689',
    projectId: 'toka-test-da174',
    storageBucket: 'toka-test-da174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuiTKpfOeZFktEV3gCBaQe1j28EAhL1M',
    appId: '1:83211892689:ios:dffdbe26121e64ca2c12f0',
    messagingSenderId: '83211892689',
    projectId: 'toka-test-da174',
    storageBucket: 'toka-test-da174.firebasestorage.app',
    iosBundleId: 'com.example.tokaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQuiTKpfOeZFktEV3gCBaQe1j28EAhL1M',
    appId: '1:83211892689:ios:dffdbe26121e64ca2c12f0',
    messagingSenderId: '83211892689',
    projectId: 'toka-test-da174',
    storageBucket: 'toka-test-da174.firebasestorage.app',
    iosBundleId: 'com.example.tokaTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl66HbWlM5ix8BKJRGwPbI7OMhzS1mrd8',
    appId: '1:83211892689:web:c94e9f536e539f3c2c12f0',
    messagingSenderId: '83211892689',
    projectId: 'toka-test-da174',
    authDomain: 'toka-test-da174.firebaseapp.com',
    storageBucket: 'toka-test-da174.firebasestorage.app',
    measurementId: 'G-DP99TNR3YE',
  );
}
